LAS v1.4
3dgeo-heidelberg/helios pull request #40
Opened 2021-05-20 13:48 UTC by miguelyermo-heidelberg

Implementation of writing LAS v1.4 files.

Please, check that the newly LAS v1.4 generated files are properly opened by your favourite viewers.
I've checked them with FugroViewer and CloudCompare without problem and tested them with some LASTools validation tools.

Notes:
 - Updated minor version in the .las file header
 - Updated header size to fit ASRS specification
 - GPS Standard Time flag set to 1 in the Global Encoding variable
 - Added support for up to 256 classes
 - Added support for up to 15 returns per pulse
 - Added some new class labels as indicated in the ASPRS v1.4 r15 standard
 - Fixed typo in TRANSMISSION_TOWER class label. Now is correctly set to 15.
 - Added ability to choose between write LAS v1.0 and LAS v1.4 through --las10 flag

2021-05-20 14:43 UTC, lwiniwar requested changes
Code-wise it looks very good to me - will still need to test.
In the meantime, could you also make the --las10 option available from pyhelios?

2021-05-20 14:51 UTC, miguelyermo-heidelberg commented
> Code-wise it looks very good to me - will still need to test.
> In the meantime, could you also make the --las10 option available from pyhelios?

Sure, let me investigate a bit.

2021-06-02 14:12 UTC, lwiniwar approved these changes

2021-06-02 14:37 UTC, lwiniwar reviewed
checked output with lastools and cloudcompare, works as expected.

2021-06-02 14:37 UTC, merged