Added implementations
3dgeo-heidelberg/helios pull request #50
Opened 2021-06-17 17:01 UTC by mark-searle99

Fully implemented detailedVoxel object loader and made translation work for voxel object loader.

2021-06-22 09:47 UTC, lwiniwar requested changes
Nice work! When running the xyzVoxelLoader, I noticed an offset in the position of the points and the voxel structure by half a voxel. Maybe this could be included in the applyTransformation function?
![grafik](https://user-images.githubusercontent.com/24376088/122903261-84462a00-d34f-11eb-9e86-a0e0298c9e43.png)

Please try it and test it using `data\surveys\voxels\tls_sphere_xyzloader.xml`
Thanks!

2021-07-19 09:25 UTC, mark-searle99 reviewed
Looks good.

2021-07-26 07:39 UTC, lwiniwar commented
interesting. let's keep this in mind for investigation in the future.

2021-07-26 07:39 UTC, lwiniwar approved these changes

2021-07-26 07:39 UTC, merged